### ISSUE TITLE
Add integration for Django

### ISSUE THREAD

**Issue by thammerl** [QloudNetwork/qloud-integrations#11]
Mathias Frey, one of our friends & family testers, would like to try out Qloud Authentication. He would use Python resp. Django for that. Therefore, we should add an integration to make it as easy as possible for him and our future Python users.

> Ja, ich bau's in Django gern ein. Mit einem halbwegs smarten pip package kannst eh mit minimalen Änderungen dann auch flask und fastapi abdecken

**Comment by mjakl** [comment]
Django offers a sophisticated user management on its own, we'll concentrate on frameworks that lack this for the time being. As a workaround: the WSGI module can be used with Django.
Won't fix for now.
